<a href="https://colab.research.google.com/github/RutujaBidkar/Python_Workshop/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [21]:
s = pd.Series([10,20,30,40,50])
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [6]:
s.dtype

dtype('int64')

In [20]:
s.values

array([10, 20, 30, 40, 50])

In [8]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [9]:
print(s.name)

None

In [10]:
s.name ="num"
print(s.name)

num

In [11]:
s[0]

np.int64(10)

In [12]:
s[0:2]  #start(included): stop (excluded): step value(values to jump)

0    10
1    20
Name: num, dtype: int64

In [13]:
s[2:4]

2    30
3    40
Name: num, dtype: int64

In [14]:
#iloc -> Location based indexing
s.iloc[3]

np.int64(40)

In [16]:
s.iloc[[1,3,4]]

1    20
3    40
4    50
Name: num, dtype: int64

In [17]:
index = ["apple","banana","grapes","orange","strawberry"]

In [26]:
s.index = index
s

apple         10
banana        20
grapes        30
orange        40
strawberry    50
dtype: int64

In [27]:
s['grapes']

np.int64(30)

In [28]:
s.iloc[3]

np.int64(40)

In [30]:
#loc -> label based index
s.loc[['grapes','apple']]

grapes    30
apple     10
dtype: int64

In [ ]:
#In label based indexing your start as well as stop value both are included in the output

In [32]:
fruit_protein ={
    "Avocado" : 2.0,
    "guva" : 2.6,
    "Blackberries": 2.0,
    "Oranges" : 0.9,
    "Banana" : 1.1,
    "Apples" : 0.3,
    "Kiwi": 1.1,
    "Pomegranate" : 1.7,
    "Mango" : 0.8,
    "cherries" : 1.0
}

In [33]:
s2 = pd.Series(fruit_protein, name = "Protein")
s2

Avocado         2.0
guva            2.6
Blackberries    2.0
Oranges         0.9
Banana          1.1
Apples          0.3
Kiwi            1.1
Pomegranate     1.7
Mango           0.8
cherries        1.0
dtype: float64

In [ ]:
#Conditional Selection

In [35]:
s2[s2>1]

Avocado         2.0
guva            2.6
Blackberries    2.0
Banana          1.1
Kiwi            1.1
Pomegranate     1.7
dtype: float64

In [40]:
#Logical Operators and or not
s2[(s2>0.5) & (s2<=2)]

Avocado         2.0
Blackberries    2.0
Oranges         0.9
Banana          1.1
Kiwi            1.1
Pomegranate     1.7
Mango           0.8
cherries        1.0
dtype: float64

In [41]:
s2[(s2>0.5) | (s2<=2)]

Avocado         2.0
guva            2.6
Blackberries    2.0
Oranges         0.9
Banana          1.1
Apples          0.3
Kiwi            1.1
Pomegranate     1.7
Mango           0.8
cherries        1.0
dtype: float64

In [42]:
#not operation:
s2[~(s2>1)]

Oranges     0.9
Apples      0.3
Mango       0.8
cherries    1.0
dtype: float64

In [44]:
#Modyfying the series:
s2["Mango"] = 2.8
s2

Avocado         2.0
guva            2.6
Blackberries    2.0
Oranges         0.9
Banana          1.1
Apples          0.3
Kiwi            1.1
Pomegranate     1.7
Mango           2.8
cherries        1.0
dtype: float64

In [47]:
#DataFrame:
data = {
    "Name" : ["Alice","Bob","Charlie","David","Eve","Alice"],
    "Age" : [25,30,35,23,29,25],
    "Department": ["HR","IT","Finance","IT","HR","HR"],
    "Salary" : [50000,60000,700000,62000,35000,50000]
}

In [48]:
data

{'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Alice'],
 'Age': [25, 30, 35, 23, 29, 25],
 'Department': ['HR', 'IT', 'Finance', 'IT', 'HR', 'HR'],
 'Salary': [50000, 60000, 700000, 62000, 35000, 50000]}

In [50]:
df = pd.DataFrame(data)
df

      Name  Age Department  Salary
0    Alice   25         HR   50000
1      Bob   30         IT   60000
2  Charlie   35    Finance  700000
3    David   23         IT   62000
4      Eve   29         HR   35000
5    Alice   25         HR   50000

In [52]:
df.head(2)

    Name  Age Department  Salary
0  Alice   25         HR   50000
1    Bob   30         IT   60000

In [53]:
df.tail(2)

    Name  Age Department  Salary
4    Eve   29         HR   35000
5  Alice   25         HR   50000

In [54]:
#loc and iloc
df.iloc[1:3]

      Name  Age Department  Salary
1      Bob   30         IT   60000
2  Charlie   35    Finance  700000

In [56]:
df.loc[1:3,["Age", "Department"]]

   Age Department
1   30         IT
2   35    Finance
3   23         IT

In [57]:
df.iloc[1:3,:2] #rows, columns

      Name  Age
1      Bob   30
2  Charlie   35

In [58]:
df["Age"]

0    25
1    30
2    35
3    23
4    29
5    25
Name: Age, dtype: int64

In [60]:
df[["Age","Department"]]

   Age Department
0   25         HR
1   30         IT
2   35    Finance
3   23         IT
4   29         HR
5   25         HR

In [62]:
df.drop("Age",axis =1)

      Name Department  Salary
0    Alice         HR   50000
1      Bob         IT   60000
2  Charlie    Finance  700000
3    David         IT   62000
4      Eve         HR   35000
5    Alice         HR   50000