<a href="https://colab.research.google.com/github/RutujaBidkar/Python_Workshop/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [ ]:
s = pd.Series([10,20,30,40,50])
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [ ]:
s.dtype

dtype('int64')

In [ ]:
s.values

array([10, 20, 30, 40, 50])

In [ ]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
print(s.name)

None

In [ ]:
s.name ="num"
print(s.name)

num

In [ ]:
s[0]

np.int64(10)

In [ ]:
s[0:2]  #start(included): stop (excluded): step value(values to jump)

0    10
1    20
Name: num, dtype: int64

In [ ]:
s[2:4]

2    30
3    40
Name: num, dtype: int64

In [ ]:
#iloc -> Location based indexing
s.iloc[3]

np.int64(40)

In [ ]:
s.iloc[[1,3,4]]

1    20
3    40
4    50
Name: num, dtype: int64

In [ ]:
index = ["apple","banana","grapes","orange","strawberry"]

In [ ]:
s.index = index
s

apple         10
banana        20
grapes        30
orange        40
strawberry    50
dtype: int64

In [ ]:
s['grapes']

np.int64(30)

In [ ]:
s.iloc[3]

np.int64(40)

In [ ]:
#loc -> label based index
s.loc[['grapes','apple']]

grapes    30
apple     10
dtype: int64

In [ ]:
#In label based indexing your start as well as stop value both are included in the output

In [ ]:
fruit_protein ={
    "Avocado" : 2.0,
    "guva" : 2.6,
    "Blackberries": 2.0,
    "Oranges" : 0.9,
    "Banana" : 1.1,
    "Apples" : 0.3,
    "Kiwi": 1.1,
    "Pomegranate" : 1.7,
    "Mango" : 0.8,
    "cherries" : 1.0
}

In [ ]:
s2 = pd.Series(fruit_protein, name = "Protein")
s2

Avocado         2.0
guva            2.6
Blackberries    2.0
Oranges         0.9
Banana          1.1
Apples          0.3
Kiwi            1.1
Pomegranate     1.7
Mango           0.8
cherries        1.0
dtype: float64

In [ ]:
#Conditional Selection

In [ ]:
s2[s2>1]

Avocado         2.0
guva            2.6
Blackberries    2.0
Banana          1.1
Kiwi            1.1
Pomegranate     1.7
dtype: float64

In [ ]:
#Logical Operators and or not
s2[(s2>0.5) & (s2<=2)]

Avocado         2.0
Blackberries    2.0
Oranges         0.9
Banana          1.1
Kiwi            1.1
Pomegranate     1.7
Mango           0.8
cherries        1.0
dtype: float64

In [ ]:
s2[(s2>0.5) | (s2<=2)]

Avocado         2.0
guva            2.6
Blackberries    2.0
Oranges         0.9
Banana          1.1
Apples          0.3
Kiwi            1.1
Pomegranate     1.7
Mango           0.8
cherries        1.0
dtype: float64

In [ ]:
#not operation:
s2[~(s2>1)]

Oranges     0.9
Apples      0.3
Mango       0.8
cherries    1.0
dtype: float64

In [ ]:
#Modyfying the series:
s2["Mango"] = 2.8
s2

Avocado         2.0
guva            2.6
Blackberries    2.0
Oranges         0.9
Banana          1.1
Apples          0.3
Kiwi            1.1
Pomegranate     1.7
Mango           2.8
cherries        1.0
dtype: float64

In [3]:
#DataFrame:
data = {
    "Name" : ["Alice","Bob","Charlie","David","Eve","Alice"],
    "Age" : [25,30,35,23,29,25],
    "Department": ["HR","IT","Finance","IT","HR","HR"],
    "Salary" : [50000,60000,700000,62000,35000,50000]
}

In [4]:
data

{'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Alice'],
 'Age': [25, 30, 35, 23, 29, 25],
 'Department': ['HR', 'IT', 'Finance', 'IT', 'HR', 'HR'],
 'Salary': [50000, 60000, 700000, 62000, 35000, 50000]}

In [9]:
df = pd.DataFrame(data)
df

      Name  Age Department  Salary
0    Alice   25         HR   50000
1      Bob   30         IT   60000
2  Charlie   35    Finance  700000
3    David   23         IT   62000
4      Eve   29         HR   35000
5    Alice   25         HR   50000

In [ ]:
df.head(2)

    Name  Age Department  Salary
0  Alice   25         HR   50000
1    Bob   30         IT   60000

In [ ]:
df.tail(2)

    Name  Age Department  Salary
4    Eve   29         HR   35000
5  Alice   25         HR   50000

In [ ]:
#loc and iloc
df.iloc[1:3]

      Name  Age Department  Salary
1      Bob   30         IT   60000
2  Charlie   35    Finance  700000

In [ ]:
df.loc[1:3,["Age", "Department"]]

   Age Department
1   30         IT
2   35    Finance
3   23         IT

In [ ]:
df.iloc[1:3,:2] #rows, columns

      Name  Age
1      Bob   30
2  Charlie   35

In [ ]:
df["Age"]

0    25
1    30
2    35
3    23
4    29
5    25
Name: Age, dtype: int64

In [ ]:
df[["Age","Department"]]

   Age Department
0   25         HR
1   30         IT
2   35    Finance
3   23         IT
4   29         HR
5   25         HR

In [ ]:
df.drop("Age",axis =1)

      Name Department  Salary
0    Alice         HR   50000
1      Bob         IT   60000
2  Charlie    Finance  700000
3    David         IT   62000
4      Eve         HR   35000
5    Alice         HR   50000

In [ ]:
df.shape

(6, 4)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        6 non-null      object
 1   Age         6 non-null      int64
 2   Department  6 non-null      object
 3   Salary      6 non-null      int64
dtypes: int64(2), object(2)
memory usage: 324.0+ bytes

In [10]:
df.describe()

             Age         Salary
count   6.000000       6.000000
mean   27.833333  159500.000000
std     4.400758  264963.204993
min    23.000000   35000.000000
25%    25.000000   50000.000000
50%    27.000000   55000.000000
75%    29.750000   61500.000000
max    35.000000  700000.000000

In [13]:
#Broadcasting
df["Salary"] = df["Salary"]+5000
df["Salary"]

0     65000
1     75000
2    715000
3     77000
4     50000
5     65000
Name: Salary, dtype: int64

In [15]:
#Renaming column :
df.rename(columns = {"Department": "Dept"},inplace = True)
df

      Name  Age     Dept  Salary
0    Alice   25       HR   65000
1      Bob   30       IT   75000
2  Charlie   35  Finance  715000
3    David   23       IT   77000
4      Eve   29       HR   50000
5    Alice   25       HR   65000

In [17]:
df["Dept"].unique()

array(['HR', 'IT', 'Finance'], dtype=object)

In [18]:
df["Dept"].value_counts()

Dept
HR         3
IT         2
Finance    1
Name: count, dtype: int64

In [20]:
df["promoted Salary"] = df["Salary"] *10
df

      Name  Age     Dept  Salary  promoted Salary
0    Alice   25       HR   65000           650000
1      Bob   30       IT   75000           750000
2  Charlie   35  Finance  715000          7150000
3    David   23       IT   77000           770000
4      Eve   29       HR   50000           500000
5    Alice   25       HR   65000           650000

In [21]:
#Data Cleaning
df.isnull().sum()

Name               0
Age                0
Dept               0
Salary             0
promoted Salary    0
dtype: int64

In [22]:
df.dropna()           #delete Null value

      Name  Age     Dept  Salary  promoted Salary
0    Alice   25       HR   65000           650000
1      Bob   30       IT   75000           750000
2  Charlie   35  Finance  715000          7150000
3    David   23       IT   77000           770000
4      Eve   29       HR   50000           500000
5    Alice   25       HR   65000           650000

In [23]:
df.dropna(how = "any")      #any row that had any null value

      Name  Age     Dept  Salary  promoted Salary
0    Alice   25       HR   65000           650000
1      Bob   30       IT   75000           750000
2  Charlie   35  Finance  715000          7150000
3    David   23       IT   77000           770000
4      Eve   29       HR   50000           500000
5    Alice   25       HR   65000           650000

In [24]:
df.dropna(how = "all") #if all the values in any row are null

      Name  Age     Dept  Salary  promoted Salary
0    Alice   25       HR   65000           650000
1      Bob   30       IT   75000           750000
2  Charlie   35  Finance  715000          7150000
3    David   23       IT   77000           770000
4      Eve   29       HR   50000           500000
5    Alice   25       HR   65000           650000

In [25]:
df["Age"].fillna(df["Age"].mean())

0    25
1    30
2    35
3    23
4    29
5    25
Name: Age, dtype: int64

In [27]:
df["Salary"].fillna(df["Salary"].median())

0     65000
1     75000
2    715000
3     77000
4     50000
5     65000
Name: Salary, dtype: int64

In [ ]:
#forward Fill : Move from Top to bottom
#backward Fill : move from bottom to top

In [28]:
df["Age"].fillna(method = "ffill")

/tmp/ipykernel_994/544980945.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Age"].fillna(method = "ffill")

0    25
1    30
2    35
3    23
4    29
5    25
Name: Age, dtype: int64

In [29]:
df["Age"].fillna(method = "bfill")

/tmp/ipykernel_994/3026805218.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Age"].fillna(method = "bfill")

0    25
1    30
2    35
3    23
4    29
5    25
Name: Age, dtype: int64

In [30]:
df["Name"].replace("Charlie","Rose")

0    Alice
1      Bob
2     Rose
3    David
4      Eve
5    Alice
Name: Name, dtype: object

In [31]:
df

      Name  Age     Dept  Salary  promoted Salary
0    Alice   25       HR   65000           650000
1      Bob   30       IT   75000           750000
2  Charlie   35  Finance  715000          7150000
3    David   23       IT   77000           770000
4      Eve   29       HR   50000           500000
5    Alice   25       HR   65000           650000

In [ ]:
#duplicate values

In [33]:
df_dup = df[df.duplicated(keep ="first")]
df_dup

    Name  Age Dept  Salary  promoted Salary
5  Alice   25   HR   65000           650000

In [34]:
df = df.drop_duplicates()
df

      Name  Age     Dept  Salary  promoted Salary
0    Alice   25       HR   65000           650000
1      Bob   30       IT   75000           750000
2  Charlie   35  Finance  715000          7150000
3    David   23       IT   77000           770000
4      Eve   29       HR   50000           500000

In [35]:
#Invaild values :
#lambda -> python
df["promoted Salary"] = df['promoted Salary'].apply(lambda x: x/10 if x > 650000 else x)

/tmp/ipykernel_994/3132034496.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["promoted Salary"] = df['promoted Salary'].apply(lambda x: x/10 if x > 650000 else x)

In [36]:
df

      Name  Age     Dept  Salary  promoted Salary
0    Alice   25       HR   65000         650000.0
1      Bob   30       IT   75000          75000.0
2  Charlie   35  Finance  715000         715000.0
3    David   23       IT   77000          77000.0
4      Eve   29       HR   50000         500000.0

In [ ]:
name = "Alice_ fernandes"
df[["first_name","Last_name"]] = df["name"].str.split("_")

In [ ]:
# apply and lambda
def multipliying_age(x):
  return x*2

df["Age"]= df["Age"].apply(multipliying_age)

In [38]:
df["Age"] = df["Age"].apply(lambda x:x/2)
df

/tmp/ipykernel_994/1084472092.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Age"] = df["Age"].apply(lambda x:x/2)

      Name   Age     Dept  Salary  promoted Salary
0    Alice  6.25       HR   65000         650000.0
1      Bob  7.50       IT   75000          75000.0
2  Charlie  8.75  Finance  715000         715000.0
3    David  5.75       IT   77000          77000.0
4      Eve  7.25       HR   50000         500000.0

In [41]:
#Join and Merges
department_info = {
    "Department" : ["HR","IT","Finance"],
    "Location" : ["New York", "San Farancisco", "chicago"],
    "Manager" : ["Laura","Steve", "Nina"]
}
df2= pd.DataFrame(department_info)
df2

  Department        Location Manager
0         HR        New York   Laura
1         IT  San Farancisco   Steve
2    Finance         chicago    Nina

In [42]:
#concat
pd.concat([df,df2])

,Name,Age,Dept,Salary,promoted Salary,Department,Location,Manager
0,Alice,6.25,HR,65000.0,650000.0,NaN,NaN,NaN
1,Bob,7.50,IT,75000.0,75000.0,NaN,NaN,NaN
2,Charlie,8.75,Finance,715000.0,715000.0,NaN,NaN,NaN
3,David,5.75,IT,77000.0,77000.0,NaN,NaN,NaN
4,Eve,7.25,HR,50000.0,500000.0,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,HR,New York,Laura
1,NaN,NaN,NaN,NaN,NaN,IT,San Farancisco,Steve
2,NaN,NaN,NaN,NaN,NaN,Finance,chicago,Nina

In [43]:
pd.concat([df,df2],axis = 1)

,Name,Age,Dept,Salary,promoted Salary,Department,Location,Manager
0,Alice,6.25,HR,65000,650000.0,HR,New York,Laura
1,Bob,7.50,IT,75000,75000.0,IT,San Farancisco,Steve
2,Charlie,8.75,Finance,715000,715000.0,Finance,chicago,Nina
3,David,5.75,IT,77000,77000.0,NaN,NaN,NaN
4,Eve,7.25,HR,50000,500000.0,NaN,NaN,NaN

In [48]:
#pd.merge(df,df2,on ="Dept")

In [ ]:
#Importing File
data = pd.read_csv()

In [ ]:
data.shape

In [51]:
data.info()

In [54]:
#convert date time ot object
data['date'] = pd.to_datetime(data['date'])

In [ ]:
data.info()